### PR TITLE
Mr/extend layout with options

### PR DESCRIPTION
**Pull request by fractaledmind**
This PR does what #18 does, but adds specs

### CODE REVIEW

**Comment by rwz** [comment]
This looks good. Mind rebasing against latest master, squashing all commits into one and adding some README examples of the new feature?

**Comment by smargh** [comment]
Done (I believe)

**Comment by rwz** [comment]
Welp, the branch is still unmergable due to conflicts and the commit contains some changes made by me in master.

**Comment by rwz** [comment]
I have your branch fully rebased here: https://github.com/rwz/nestive/tree/layout-options

It's not passing specs because the `extended_with_options` template is missing. You can rewrite your PR using this branch and fix it by adding missing layout.

Update: I've just noticed that you've somehow managed to lose the most of the changes of the original PR. You'd need to restore them as well.

**Comment by fractaledmind** [comment]
That's what I get for trying to git at 2am. I'll start over and get this straight.

**Pull request closed without merging**
