### PR TITLE
Consider additional parameters when extending layouts

### PR DESCRIPTION
**Pull request by arielsvn**
This gem is great by the way, I have been using it for a while without any issues.

I came to a scenario where it would be great to allow the views extending a layout to pass information to the layout. This could be done with the extend method, passing an additional variable, something like this:

``` erb
<%= extends :application, wide: true do %>
  <% append :sidebar, "More content." %>
<% end %>
```

And then in `app/views/layouts/application.html.erb`, that variable can be used:

``` erb
<!DOCTYPE html>
  <html>
  <body>
    <% if wide %>
      ... do something
    <% end %>

    <%= yield %>
  </body>
</html>
```

### CODE REVIEW

**Comment by rwz** [comment]
Could you add some tests for this?

**Comment by halilim** [comment]
+1 for this.

**Comment by PatLeb** [comment]
+1

**Comment by rwz** [comment]
I'm not gonna merge it without tests.

**Comment by PatLeb** [comment]
It might not be a good idea, I tried it and it didn't work at all.

**Comment by fractaledmind** [comment]
PR #29 adds this functionality along with some tests.

**Pull request closed without merging**
